version: '3.3'

services:
    influxdb:
        image: influxdb:latest
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ./volumes/influxdb:/var/lib/influxdb:rw
        ports:
            - 8086:8086
            - 8083:8083
        environment:
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=jangkrik

    grafana:
        image: grafana/grafana:5.0.0 
        deploy:
            restart_policy:
                 condition: on-failure
        volumes:
            - ./volumes/grafana:/var/lib/grafana
        ports:
            - 4500:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=air0805.
            - GF_AUTH_ANONYMOUS_ENABLED=true
